server:
  port: 8081

jwt:
  # Lee el secreto del JWT desde la variable de entorno
  secret: ${JWT_SECRET:845901478c39728dd8e43a08173831bccf0cc10a86e2d854de11bd1b4a8d0623}

spring:
  cloud:
    gateway:
      default-filters:
        - PreserveHostHeader
      routes:
        # --- RUTA PARA AUTHENTICATION-SERVICE ---
        - id: authentication-service
          # Lee la URL del servicio desde una variable de entorno
          uri: ${AUTH_SERVICE_URL:http://localhost:8082}
          predicates:
            - Path=/auth/**, /password/**, /api/admin/users/**

        # --- RUTA CONSOLIDADA PARA AGENDAMIENTO-SERVICE ---
        - id: agendamiento-service
          uri: ${AGENDAMIENTO_SERVICE_URL:http://localhost:8083}
          predicates:
            - Path=/servicios/**, /historial/**, /veterinarios/**, /propietarios/**, /mascotas/**, /actualizar/**, /especialidad/**, /disponibilidad/**, /cita/**, /AreaClinica/**, /agenda/**, /imagenes/mascotas/**

        # --- RUTA CONSOLIDADA PARA PERFIL-SERVICE ---
        - id: perfil-service
          uri: ${PERFIL_SERVICE_URL:http://localhost:8085}
          predicates:
            - Path=/perfil/**

        # --- RUTA PARA EMAIL-SERVICE ---
        - id: email-service
          uri: ${EMAIL_SERVICE_URL:http://localhost:8084}
          predicates:
            - Path=/email-service/**
          filters:
            - StripPrefix=1

        - id: product-service
          uri: ${PRODUCT_SERVICE_URL:http://localhost:5001}
          predicates:
            - Path=/productos/**, /categorias/**, /cart/**, /orders/**, /checkout/**, /stripe-webhook, /api/admin/**, /static/uploads/products/**