server:
  port: 8081

jwt:
  secret: 845901478c39728dd8e43a08173831bccf0cc10a86e2d854de11bd1b4a8d0623


spring:
  cloud:
    gateway:
      default-filters:
        - PreserveHostHeader
      routes:
        - id: authentication-service
          uri: http://localhost:8082
          predicates:
            - Path=/auth/**, /password/**, /api/admin/**



        - id: agendamiento-service
          uri: http://localhost:8083
          predicates:
            - Path=/servicios/**

        - id: agendamiento-service
          uri: http://localhost:8083
          predicates:
            - Path=/veterinarios/**


        - id: agendamiento-service-propietarios
          uri: http://localhost:8083
          predicates:
            - Path=/propietarios/**


        - id: agendamiento-service-mascotas
          uri: http://localhost:8083
          predicates:
            - Path=/mascotas/**


        - id: agendamiento-service-especialidad
          uri: http://localhost:8083
          predicates:
            - Path=/especialidad/**


        - id: agendamiento-service-disponibilidad
          uri: http://localhost:8083
          predicates:
            - Path=/disponibilidad/**


        - id: agendamiento-service-citas
          uri: http://localhost:8083
          predicates:
            - Path=/cita/**


        - id: agendamiento-service-historial
          uri: http://localhost:8083
          predicates:
            - Path=/historial/**


        - id: agendamiento-service-areas-clinicas
          uri: http://localhost:8083
          predicates:
            - Path=/AreaClinica/**


        - id: agendamiento-service-agendas
          uri: http://localhost:8083
          predicates:
            - Path=/agenda/**


        - id: agendamiento-service-imagenes
          uri: http://localhost:8083
          predicates:
            - Path=/imagenes/mascotas/**




        - id: perfil-service
          uri: http://localhost:8085
          predicates:
              - Path=/perfil/**




        - id: email-service
          uri: http://localhost:8084
          predicates:
            - Path=/email-service/**
          filters:
            - StripPrefix=1

        - id: product-service
          uri: http://localhost:5001
          predicates:
            - Path=/productos/**, /categorias/**



        - id: product-static-images
          uri: http://localhost:5001 # Apunta al servicio de Python
          predicates:
            - Path=/static/uploads/products/** # La ruta donde se guardan las imágenes














