server:
  port: 8081

jwt:
  secret: 845901478c39728dd8e43a08173831bccf0cc10a86e2d854de11bd1b4a8d0623


spring:
  cloud:
    gateway:
      routes:
        - id: authentication-service
          uri: http://localhost:8082
          predicates:
            - Path=/auth/**

        - id: agendamiento-service
          uri: http://localhost:8083
          predicates:
            - Path=/veterinarios/**


        - id: agendamiento-service
          uri: http://localhost:8083
          predicates:
            - Path=/propietarios/**


        - id: email-service
          uri: http://localhost:8084
          predicates:
            - Path=/email-service/**
          filters:
            - StripPrefix=1







