server:
  port: 8085

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/perfildb?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password: 3712
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  application:
    name: perfil-service

jwt:
  secret: 845901478c39728dd8e43a08173831bccf0cc10a86e2d854de11bd1b4a8d0623

# Configuración para servicios externos
services:
  email:
    url: http://localhost:8081/email-service
  authentication:
    url: http://localhost:8082


agendamiento:
  service:
    url: http://localhost:8083 # URL del servicio de agendamiento


authentication:
  service:
    url: http://localhost:8082 # URL del servicio de autenticación