server:
  port: 8085

spring:
  datasource:
    url: ${DB_URL_PERFIL}
    username: root
    password: ${DB_ROOT_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  application:
    name: perfil-service

jwt:
  secret: ${JWT_SECRET:845901478c39728dd8e43a08173831bccf0cc10a86e2d854de11bd1b4a8d0623}

# AÑADIMOS LAS URLs DE SERVICIOS EXTERNOS LEYENDO DESDE VARIABLES DE ENTORNO
agendamiento:
  service:
    url: ${AGENDAMIENTO_SERVICE_URL:http://localhost:8083}

authentication:
  service:
    url: ${AUTH_SERVICE_URL:http://localhost:8082} # <-- ESTA LÍNEA ES LA CORRECCIÓN CLAVE

app:
  upload:
    dir: ./uploads/profile-images